# Day 4 - Exploring Data with Pandas

This notebook demonstrates how to load, inspect, clean, filter, and summarize a dataset using Pandas.

# Pandas Data Structures

Pandas provides two main data structures for working with data:

### Series
A Series is a one-dimensional labeled array that stores a single column of data.

### DataFrame
A DataFrame is a two-dimensional table with rows and columns, similar to an Excel spreadsheet. It is made up of multiple Series objects.

In [4]:
import pandas as pd

#Example 1: Create a Series from a list
ages = pd.Series([20, 22, 19, 21], name="Age")

print(ages)

#Example 2: Create a DataFrame from a dictionary
students = {
    "Name": ["Aya", "Ali", "Sara"],
    "Age": [22, 20, 23]
}

df = pd.DataFrame(students)

df

0    20
1    22
2    19
3    21
Name: Age, dtype: int64

   Name  Age
0   Aya   22
1   Ali   20
2  Sara   23

## Selecting Columns

We can select one or more columns from a DataFrame.

In [5]:
import pandas as pd
students ={
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [20, 21, 19, 22],
    "Grade": ["A", "B", "C", "A"],
    "Major": ["Computer Science", "Mathematics", "Physics", "Engineering"]
    
}

df = pd.DataFrame(students)
df # to display the DataFrame 
df["Name"] # to display the Name column
df[["Name", "Age"]] # to display the Name and Age columns
df.iloc[0] # to display the first row
df.loc[1,"Age"] = 22 # to update the Age of the second student (Bob) to 22
df.iloc[1] # to display the updated second row
df["city"] = ["New York", "Los Angeles", "Chicago", "Houston"] # to add a new column 'city'
df["Passed"] = df["Grade"] <= "D" # to add a new column 'Passed' based on the Grade
df = df.drop(columns = ["Passed"]) # to drop the 'Passed' column
df

      Name  Age Grade             Major         city
0    Alice   20     A  Computer Science     New York
1      Bob   22     B       Mathematics  Los Angeles
2  Charlie   19     C           Physics      Chicago
3    David   22     A       Engineering      Houston

## Reading CSV Files

A CSV (Comma-Separated Values) file stores tabular data in plain text.
Pandas provides the `read_csv()` function to load a CSV file into a DataFrame.

In [6]:
import pandas as pd
df = pd.read_csv("students.csv") # to read a CSV file into a DataFrame
df # to display the DataFrame

    Name  Age Major  Grade
0    Aya   22    CS     90
1    Ali   20    IT     85
2   Sara   23    AI     95
3   Omar   21    CS     88
4   Lina   22    IT     91
5  Ahmad   24    AI     76
6   Noor   21    CS     84
7   Rami   23    IT     79
8   Reem   20    AI     93

## Viewing the Dataset

Before analyzing data, it is important to inspect its contents.
Pandas provides functions such as `head()` and `tail()` to preview the dataset.

In [7]:
df.head() # to display the first 5 rows of the DataFrame
df.head(3) # to display the first 3 rows of the DataFrame
df.tail() # to display the last 5 rows of the DataFrame
df.tail(2) # to display the last 2 rows of the DataFrameq

   Name  Age Major  Grade
7  Rami   23    IT     79
8  Reem   20    AI     93

## Dataset Shape

The `shape` attribute returns the number of rows and columns in the dataset.

In [8]:
df.shape

(9, 4)

## Column Names

The `columns` attribute returns the names of all columns in the dataset.

In [9]:
df.columns

Index(['Name', 'Age', 'Major', 'Grade'], dtype='str')

## Dataset Information

The `info()` function displays information about the dataset, including column names, data types, and missing values.

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      str
 1   Age     9 non-null      int64
 2   Major   9 non-null      str
 3   Grade   9 non-null      int64
dtypes: int64(2), str(2)
memory usage: 420.0 bytes

## Descriptive Statistics

The `describe()` function generates summary statistics for numerical columns.

In [22]:
df.describe()

             Age      Grade
count   9.000000   9.000000
mean   21.777778  86.777778
std     1.394433   6.359595
min    20.000000  76.000000
25%    21.000000  84.000000
50%    22.000000  88.000000
75%    23.000000  91.000000
max    24.000000  95.000000

## Cleaning Data

Real-world datasets often contain missing values.
Before analyzing the data, we should identify and handle these missing values.

In [11]:
df.isnull() # to check for missing values in the DataFrame
df.isnull().sum() # to count the number of missing values in each column
df.dropna() # to drop rows with missing values
df = df.dropna() # to drop rows with missing values and update the DataFrame
df.fillna(0) # to fill missing values with 0

    Name  Age Major  Grade
0    Aya   22    CS     90
1    Ali   20    IT     85
2   Sara   23    AI     95
3   Omar   21    CS     88
4   Lina   22    IT     91
5  Ahmad   24    AI     76
6   Noor   21    CS     84
7   Rami   23    IT     79
8   Reem   20    AI     93

## Filtering Data

Filtering allows us to select only the rows that satisfy a specific condition.

In [12]:
df[df["Age"] > 20] # to filter rows where Age is greater than 20
df[df["Major"] == "CS"] # to filter rows where Major is "CS"
df[(df["Age"] > 20) & (df["Major"] == "CS")]#more than one condition
df[(df["Age"] > 20) | (df["Major"] == "CS")]

    Name  Age Major  Grade
0    Aya   22    CS     90
2   Sara   23    AI     95
3   Omar   21    CS     88
4   Lina   22    IT     91
5  Ahmad   24    AI     76
6   Noor   21    CS     84
7   Rami   23    IT     79

## Sorting Data

Sorting arranges the dataset in ascending or descending order.

In [13]:
df.sort_values("Grade") # to sort the DataFrame by the Grade column in ascending order
df.sort_values("Grade", ascending=False) # to sort the DataFrame by the Grade column in descending order
df.sort_values(["Major", "Age"]) # to sort the DataFrame by Major and then by Age

    Name  Age Major  Grade
8   Reem   20    AI     93
2   Sara   23    AI     95
5  Ahmad   24    AI     76
3   Omar   21    CS     88
6   Noor   21    CS     84
0    Aya   22    CS     90
1    Ali   20    IT     85
4   Lina   22    IT     91
7   Rami   23    IT     79

## Grouping Data

The `groupby()` function groups rows based on a column and performs calculations on each group.

In [58]:
df.groupby("Major")["Grade"].mean() # to group the DataFrame by Major and calculate the mean Grade for each Major
df.groupby("Major").size() # to group the DataFrame by Major and count the number of students in each Major
df.groupby("Major")["Grade"].max() # to group the DataFrame by Major and find the maximum Grade for each Major
df.groupby("Major")["Grade"].min()

Major
AI    76
CS    84
IT    79
Name: Grade, dtype: int64

# Hands-On Lab

In this lab, we will explore a real dataset using Pandas.
We will load the dataset, inspect it, clean it, filter it, and summarize the data.

## Task 1: Load the Dataset

Load the CSV dataset into a Pandas DataFrame.
Display the dataset shape, column names, and data types.

In [14]:
import pandas as pd

# Load the dataset
df = pd.read_csv("students.csv")

# Display dataset shape
print("Shape:", df.shape)

# Display column names
print("\nColumns:")
print(df.columns)

# Display data types
print("\nData Types:")
print(df.dtypes)

Shape: (9, 4)

Columns:
Index(['Name', 'Age', 'Major', 'Grade'], dtype='str')

Data Types:
Name       str
Age      int64
Major      str
Grade    int64
dtype: object

## Task 2: Handle Missing Values

Count the missing values in each column.
If missing values exist, handle them appropriately and explain the chosen method.

In [15]:
# Count missing values
print(df.isnull().sum())

Name     0
Age      0
Major    0
Grade    0
dtype: int64

## Task 3: Filter the Data

Filter the dataset to include only students with grades greater than or equal to 90.

In [16]:
high_grade_students = df[df["Grade"] >= 90]

high_grade_students

   Name  Age Major  Grade
0   Aya   22    CS     90
2  Sara   23    AI     95
4  Lina   22    IT     91
8  Reem   20    AI     93

## Task 4: Group the Data

Group the dataset by major and calculate the average grade for each major.

In [17]:
average_grade = df.groupby("Major")["Grade"].mean()

average_grade

Major
AI    88.000000
CS    87.333333
IT    85.000000
Name: Grade, dtype: float64